### ISSUE TITLE
Address verification improvements

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/toucan-bridge#48]
Currently we have basic regen address validation in place. This validation checks the address has a length of at least `44`. This is the length of a standard account and a group address (i.e. a group decision policy address) has a length of `64`.

We might want to consider updating address verification to include checksum verification and/or specific lengths.

https://github.com/regen-network/toucan-bridge/blob/master/contracts/ToucanRegenBridge.sol#L65-L72

**Comment by 0xmichalis** [comment]
@ryanchristo @aspiers given that the bridge contract is not upgradeable and in order to avoid a potential data migration in case we need to redeploy in the future with this fix, should this issue be fixed asap? 

@ryanchristo can you clarify the checksum verification part? Or is it enough as part of this issue to just allow addresses of length  `64`?

**Comment by ryanchristo** [comment]
There is no need for a fix but we could improve verification. The contract will support a standard account address and a group account address given we are checking `>=`. If we do not use a more strict verification in the contract, the address should be verified on the UI side to prevent a user error and I believe @lazaralex98 is already working on this.

**Comment by ryanchristo** [comment]
For checksum verification, not sure if there is a simple solution in solidity. I think we are ok without it.

**Comment by aspiers** [comment]
@ryanchristo Is it worth checking that each byte within the address is an expected character? e.g. punctuation is presumably not allowed, only alphanumeric right?

What is the checksum algorithm?  If it's not too hard / expensive to do in Solidity then I would say it's worth it - otherwise yeah, a frontend check should be good enough.

**Comment by ryanchristo** [comment]
Looking into this now.

> Is it worth checking that each byte within the address is an expected character? e.g. punctuation is presumably not allowed, only alphanumeric right?

Yea, I think this would be a good minimum check and that is correct.

> What is the checksum algorithm? If it's not too hard / expensive to do in Solidity then I would say it's worth it - otherwise yeah, a frontend check should be good enough.

I'll further investigate. I agree, I think we should decide based on the cost.
